version: '3'
services:
  dbweb:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    cpu_count: 1
    mem_reservation: 512M
    networks:
      - duckling-web-network
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - dbweb_data:/var/lib/postgresql/data
  dbmltasks:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    cpu_count: 1
    mem_reservation: 512M
    networks:
      - duckling-mltasks-network
    ports:
      - '127.0.0.1:5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - dbmltasks_data:/var/lib/postgresql/data
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    env_file:
      - ./apps/web/.env
    networks:
      - duckling-web-network
    ports:
      - '3000:3000'
    depends_on:
      - dbweb
      # - mltasks
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@dbweb:5432/postgres?schema=public'
      OLLAMA_URL: 'http://host.docker.internal:11434'
      LMSTUDIO_URL: 'http://host.docker.internal:1234'
      ML_API_URL: 'http://mltasks:8000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "pnpm run prisma:migrate &&
            pnpm run prisma:seed &&
            pnpm start"
  mltasks:
    build:
      context: ./apps/mltasks
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8000:8000'
    environment:
      REDIS_URL: 'redis://redis:6379/0'
      DATABASE_URL: 'postgresql://postgres:postgres@dbmltasks:5432/postgres'
    networks:
      - duckling-mltasks-network
      - duckling-web-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - dbmltasks
      - redis
    command: >
      sh -c "./run.sh"
  mltasks_celery_worker:
    build:
      context: ./apps/mltasks
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8000:8000'
    environment:
      REDIS_URL: 'redis://redis:6379/0'
      DATABASE_URL: 'postgresql://postgres:postgres@dbmltasks:5432/postgres'
      MLFLOW_TRACKING_SERVER_URL: 'http://mlflow:5000'
    networks:
      - duckling-mltasks-network
      - duckling-web-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - dbmltasks
      - redis
    command: >
      sh -c "make run_celery"
  redis:
    image: redis:7
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - duckling-mltasks-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 10
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.22.0
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - duckling-mltasks-network
    command: >
      mlflow server --host 0.0.0.0 --port 5000

networks:
  duckling-web-network:
  duckling-mltasks-network:

volumes:
  dbmltasks_data:
  dbweb_data:
