version: '3'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    cpu_count: 1
    mem_reservation: 512M
    networks:
      - duckling-web-network
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    env_file:
      - ./apps/web/.env
    networks:
      - duckling-web-network
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/postgres?schema=public'
      OLLAMA_URL: 'http://host.docker.internal:11434'
      LMSTUDIO_URL: 'http://host.docker.internal:1234'
    command: >
      sh -c "pnpm run prisma:migrate &&
            pnpm run prisma:seed &&
            pnpm start"

networks:
  duckling-web-network:
  duckling-services-network:

volumes:
  postgres_data:
