"""empty message

Revision ID: 476678f70f07
Revises: 6da4b99e74c5
Create Date: 2025-04-24 01:23:38.500726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476678f70f07'
down_revision: Union[str, None] = '6da4b99e74c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    split_type = sa.Enum('TRAIN', 'TEST', name='traintestsplit')
    split_type.create(op.get_bind(), checkfirst=True)
    op.add_column('text_classifier_dataset_items', sa.Column('split', split_type, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_classifier_dataset_items', 'split')
    # ### end Alembic commands ###
