"""empty message

Revision ID: 64db94edb688
Revises: 837d4ff791b8
Create Date: 2025-04-25 03:39:19.739075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64db94edb688'
down_revision: Union[str, None] = '837d4ff791b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_dataset_items_dataset_id_split_query', 'text_classifier_dataset_items', ['dataset_id', 'split', 'dataset_label_id'], unique=False, postgresql_where=sa.text('dataset_label_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dataset_items_dataset_id_split_query', table_name='text_classifier_dataset_items', postgresql_where=sa.text('dataset_label_id IS NOT NULL'))
    # ### end Alembic commands ###
