"""empty message

Revision ID: 6da4b99e74c5
Revises: c4e12e61c97d
Create Date: 2025-04-23 17:23:27.514466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6da4b99e74c5'
down_revision: Union[str, None] = 'c4e12e61c97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text_classifier_dataset_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_classifier_dataset_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('text_classifier_dataset_items_dataset_id_fkey', 'text_classifier_dataset_items', type_='foreignkey')
    op.drop_constraint('text_classifier_dataset_items_dataset_id_label_fkey', 'text_classifier_dataset_items', type_='foreignkey')
    op.create_foreign_key(None, 'text_classifier_dataset_items', 'text_classifier_dataset_labels', ['dataset_id', 'dataset_label_id'], ['dataset_id', 'dataset_label_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'text_classifier_dataset_items', 'text_classifier_datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
    op.alter_column('text_classifier_dataset_labels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_classifier_dataset_labels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('text_classifier_dataset_labels_dataset_id_fkey', 'text_classifier_dataset_labels', type_='foreignkey')
    op.create_foreign_key(None, 'text_classifier_dataset_labels', 'text_classifier_datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
    op.alter_column('text_classifier_datasets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_classifier_datasets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text_classifier_datasets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_classifier_datasets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'text_classifier_dataset_labels', type_='foreignkey')  # type: ignore
    op.create_foreign_key('text_classifier_dataset_labels_dataset_id_fkey', 'text_classifier_dataset_labels', 'text_classifier_datasets', ['dataset_id'], ['id'])
    op.alter_column('text_classifier_dataset_labels', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_classifier_dataset_labels', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'text_classifier_dataset_items', type_='foreignkey')  # type: ignore
    op.drop_constraint(None, 'text_classifier_dataset_items', type_='foreignkey')  # type: ignore
    op.create_foreign_key('text_classifier_dataset_items_dataset_id_label_fkey', 'text_classifier_dataset_items', 'text_classifier_dataset_labels', ['dataset_id', 'dataset_label_id'], ['dataset_id', 'dataset_label_id'])
    op.create_foreign_key('text_classifier_dataset_items_dataset_id_fkey', 'text_classifier_dataset_items', 'text_classifier_datasets', ['dataset_id'], ['id'])
    op.alter_column('text_classifier_dataset_items', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_classifier_dataset_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
