"""empty message

Revision ID: 6ee76a2e972f
Revises: 
Create Date: 2025-04-22 22:06:26.688145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee76a2e972f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_classifier_datasets',
    sa.Column('display_name', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_classifier_dataset_labels',
    sa.Column('dataset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('dataset_label_id', sa.UUID().with_variant(sa.String(length=256), 'sqlite'), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('color', sa.String(length=256), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['text_classifier_datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'dataset_label_id')
    )
    op.create_table('text_classifier_dataset_items',
    sa.Column('dataset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('text_content', sa.String(), nullable=False),
    sa.Column('label', sa.UUID().with_variant(sa.String(length=256), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id', 'label'], ['text_classifier_dataset_labels.dataset_id', 'text_classifier_dataset_labels.dataset_label_id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['text_classifier_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_classifier_dataset_items')
    op.drop_table('text_classifier_dataset_labels')
    op.drop_table('text_classifier_datasets')
    # ### end Alembic commands ###
