"""empty message

Revision ID: 837d4ff791b8
Revises: 476678f70f07
Create Date: 2025-04-25 01:35:35.961440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837d4ff791b8'
down_revision: Union[str, None] = '476678f70f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    model_status = sa.Enum('IDLE', 'TRAINING', 'TRAINED', 'FAILED', name='modelstatus')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_classifier_models',
    sa.Column('dataset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('dataset_model_id', sa.UUID().with_variant(sa.String(length=256), 'sqlite'), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('status', model_status, server_default='IDLE', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['text_classifier_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_classifier_models_status'), 'text_classifier_models', ['status'], unique=False)
    op.create_table('text_classifier_model_metrics',
    sa.Column('model_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['text_classifier_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_classifier_model_metrics_name'), 'text_classifier_model_metrics', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_classifier_model_metrics_name'), table_name='text_classifier_model_metrics')
    op.drop_table('text_classifier_model_metrics')
    op.drop_index(op.f('ix_text_classifier_models_status'), table_name='text_classifier_models')
    op.drop_table('text_classifier_models')
    # ### end Alembic commands ###

    op.execute('DROP TYPE IF EXISTS modelstatus;')
