"""empty message

Revision ID: acb3d67c34a5
Revises: bb10fddcc431
Create Date: 2025-04-23 03:27:51.819527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb3d67c34a5'
down_revision: Union[str, None] = 'bb10fddcc431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'text_classifier_dataset_items',
        'label',
        new_column_name='dataset_label_id'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_classifier_dataset_items', sa.Column('label', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'text_classifier_dataset_items', type_='foreignkey')
    op.create_foreign_key('text_classifier_dataset_items_dataset_id_label_fkey', 'text_classifier_dataset_items', 'text_classifier_dataset_labels', ['dataset_id', 'label'], ['dataset_id', 'dataset_label_id'])
    op.drop_column('text_classifier_dataset_items', 'dataset_label_id')
    # ### end Alembic commands ###
