"""empty message

Revision ID: b93d43f78286
Revises: 64db94edb688
Create Date: 2025-04-30 15:59:08.728089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93d43f78286'
down_revision: Union[str, None] = '64db94edb688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_classifier_models', sa.Column('celery_task_id', sa.UUID().with_variant(sa.String(length=256), 'sqlite'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_classifier_models', 'celery_task_id')
    # ### end Alembic commands ###
