"""empty message

Revision ID: bb10fddcc431
Revises: 6ee76a2e972f
Create Date: 2025-04-22 22:21:55.456825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb10fddcc431'
down_revision: Union[str, None] = '6ee76a2e972f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_classifier_dataset_items', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('text_classifier_dataset_items', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('text_classifier_dataset_labels', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('text_classifier_dataset_labels', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('text_classifier_datasets', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('text_classifier_datasets', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_classifier_datasets', 'updated_at')
    op.drop_column('text_classifier_datasets', 'created_at')
    op.drop_column('text_classifier_dataset_labels', 'updated_at')
    op.drop_column('text_classifier_dataset_labels', 'created_at')
    op.drop_column('text_classifier_dataset_items', 'updated_at')
    op.drop_column('text_classifier_dataset_items', 'created_at')
    # ### end Alembic commands ###
