"""empty message

Revision ID: c4e12e61c97d
Revises: acb3d67c34a5
Create Date: 2025-04-23 04:31:55.586647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e12e61c97d'
down_revision: Union[str, None] = 'acb3d67c34a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('text_classifier_dataset_items_dataset_id_created_at_idx', 'text_classifier_dataset_items', ['dataset_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('text_classifier_dataset_items_dataset_id_created_at_idx', table_name='text_classifier_dataset_items')
    # ### end Alembic commands ###
