"""empty message

Revision ID: d4aa7413b081
Revises: b93d43f78286
Create Date: 2025-05-16 13:04:45.331261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4aa7413b081'
down_revision: Union[str, None] = 'b93d43f78286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_classifier_models', sa.Column('mlflow_run_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_classifier_models', 'mlflow_run_id')
    # ### end Alembic commands ###
